workflows:
  react-native-android:
    name: React Native Android Build
    instance_type: mac_mini_m2
    environment:
      node: 18
    triggering:
      events:
        - push
    scripts:
      - name: Install deps and build
        script: |
          npm install
          npm install -g eas-cli
          eas build --platform android --profile preview --non-interactive
    publishing:
      email:
        recipients:
          - your-email@example.com
