workflows:
  react-native-android:
    name: React Native Android
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      node: 18
      java: 11
      android_sdk: 33
      vars:
        EXPO_PUBLIC_SERVER_URI: "https://ecommerce-dating-app.onrender.com"
    triggering:
      events:
        - push
      branch:
        patterns:
          - pattern: master
            include: true
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Test build
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        enabled: false
