import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import Toast from 'react-native-toast-message';
import axiosInstance from '@/utils/axiosinstance';

export default function SellerFinanceScreen(){
 const [accounts,setAccounts]=useState<any[]>([]);const [balance,setBalance]=useState(0);const [selected,setSelected]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [form,setForm]=useState({bankName:'',bankCode:'',accountNumber:''});
 const load=async()=>{setLoading(true);try{const [banks,ledger]=await Promise.all([axiosInstance.get('/seller/api/bank-accounts'),axiosInstance.get('/seller/api/ledger')]);setAccounts(banks.data?.data||[]);setBalance(Number(ledger.data?.availableBalance||0));const preferred=(banks.data?.data||[]).find((row:any)=>row.isDefault)||(banks.data?.data||[])[0];setSelected(preferred?._id||'');}catch(error:any){Toast.show({type:'error',text1:'Could not load seller finances',text2:error?.response?.data?.error});}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const add=async()=>{if(!form.bankName.trim()||!form.bankCode.trim()||!/^\d{10}$/.test(form.accountNumber))return Toast.show({type:'error',text1:'Enter valid bank details'});setSaving(true);try{await axiosInstance.post('/seller/api/bank-accounts',form);setForm({bankName:'',bankCode:'',accountNumber:''});await load();Toast.show({type:'success',text1:'Bank account verified'});}catch(error:any){Toast.show({type:'error',text1:'Bank verification failed',text2:error?.response?.data?.error});}finally{setSaving(false)}};
 const withdraw=async()=>{if(!selected)return Toast.show({type:'error',text1:'Select a bank account'});try{await axiosInstance.post('/seller/api/payouts',{bankAccountId:selected});Toast.show({type:'success',text1:'Withdrawal requested',text2:'An administrator must approve this transfer.'});await load();}catch(error:any){Toast.show({type:'error',text1:'Request failed',text2:error?.response?.data?.error});}};
 if(loading)return <View style={styles.center}><ActivityIndicator size="large" color="#F97316"/></View>;
 return <FlatList style={styles.screen} data={accounts} keyExtractor={item=>item._id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.balance}><Text style={styles.balanceLabel}>Available to withdraw</Text><Text style={styles.balanceValue}>₦{balance.toLocaleString()}</Text><Text style={styles.balanceHint}>Withdrawals require administrator approval and are sent only to a verified account.</Text><TouchableOpacity style={styles.withdraw} onPress={withdraw}><Text style={styles.withdrawText}>Request withdrawal</Text></TouchableOpacity></View><Text style={styles.heading}>Verified bank accounts</Text></>} renderItem={({item})=><TouchableOpacity style={[styles.account,selected===item._id&&styles.accountSelected]} onPress={()=>setSelected(item._id)}><View style={{flex:1}}><Text style={styles.accountName}>{item.bankName}</Text><Text style={styles.accountSub}>{item.accountName} · {item.accountNumber}</Text></View><View style={[styles.radio,selected===item._id&&styles.radioActive]}/></TouchableOpacity>} ListFooterComponent={<View style={styles.form}><Text style={styles.heading}>Add another bank</Text><TextInput style={styles.input} value={form.bankName} onChangeText={bankName=>setForm({...form,bankName})} placeholder="Bank name" placeholderTextColor="#9CA3AF"/><TextInput style={styles.input} value={form.bankCode} onChangeText={bankCode=>setForm({...form,bankCode})} placeholder="Paystack bank code" placeholderTextColor="#9CA3AF"/><TextInput style={styles.input} value={form.accountNumber} onChangeText={accountNumber=>setForm({...form,accountNumber})} placeholder="10-digit account number" placeholderTextColor="#9CA3AF" keyboardType="number-pad" maxLength={10}/><TouchableOpacity style={styles.add} onPress={add} disabled={saving}>{saving?<ActivityIndicator color="#FFF"/>:<Text style={styles.withdrawText}>Verify and add bank</Text>}</TouchableOpacity></View>}/>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F7F9'},content:{padding:16,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center'},balance:{backgroundColor:'#111827',borderRadius:20,padding:22},balanceLabel:{color:'#D1D5DB',fontSize:13,fontWeight:'600'},balanceValue:{color:'#FFF',fontSize:32,fontWeight:'900',marginTop:7},balanceHint:{color:'#9CA3AF',fontSize:12,lineHeight:18,marginTop:8},withdraw:{height:48,backgroundColor:'#F97316',borderRadius:13,alignItems:'center',justifyContent:'center',marginTop:18},withdrawText:{color:'#FFF',fontWeight:'800'},heading:{fontSize:18,fontWeight:'900',color:'#111827',marginTop:24,marginBottom:12},account:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E5E7EB',borderRadius:14,padding:15,flexDirection:'row',alignItems:'center',marginBottom:10},accountSelected:{borderColor:'#F97316',backgroundColor:'#FFF7ED'},accountName:{fontSize:15,fontWeight:'800',color:'#111827'},accountSub:{fontSize:12,color:'#6B7280',marginTop:4},radio:{width:20,height:20,borderRadius:10,borderWidth:2,borderColor:'#D1D5DB'},radioActive:{borderWidth:6,borderColor:'#F97316'},form:{marginTop:5},input:{height:52,backgroundColor:'#FFF',borderWidth:1,borderColor:'#D1D5DB',borderRadius:13,paddingHorizontal:15,color:'#111827',marginBottom:11},add:{height:50,backgroundColor:'#0F766E',borderRadius:13,alignItems:'center',justifyContent:'center'}});
