import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import Toast from 'react-native-toast-message';
import axiosInstance from '@/utils/axiosinstance';

export default function CommerceApprovalsScreen() {
  const params = useLocalSearchParams<{ tab?: string }>();
  const [tab, setTab] = useState<'products'|'payouts'>(params.tab === 'payouts' ? 'payouts' : 'products');
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [rejecting, setRejecting] = useState<any>(null);
  const [reason, setReason] = useState('');
  const load = async () => { setLoading(true); try { const response = await axiosInstance.get(tab === 'products' ? '/admin/api/products?status=pending' : '/admin/api/payouts?status=requested'); setItems(response.data?.data || []); } catch (error: any) { Toast.show({ type:'error', text1:'Could not load approvals', text2:error?.response?.data?.message || error?.response?.data?.error }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [tab]);
  const approve = async (item:any) => { try { await axiosInstance.post(`/admin/api/${tab}/${item._id}/approve`); setItems(current => current.filter(row => row._id !== item._id)); Toast.show({type:'success',text1:tab === 'products' ? 'Listing is now live' : 'Withdrawal approved'}); } catch(error:any){Toast.show({type:'error',text1:'Approval failed',text2:error?.response?.data?.error});} };
  const reject = async () => { if(!reason.trim()) return; try { await axiosInstance.post(`/admin/api/${tab}/${rejecting._id}/reject`,{reason:reason.trim()}); setItems(current=>current.filter(row=>row._id!==rejecting._id)); setRejecting(null);setReason('');Toast.show({type:'success',text1:'Rejected'}); } catch(error:any){Toast.show({type:'error',text1:'Rejection failed',text2:error?.response?.data?.error});} };
  const render = ({item}:any) => <View style={styles.card}>{tab === 'products' ? <><View style={styles.productTop}>{item.images?.[0]?.url ? <Image source={{uri:item.images[0].url}} style={styles.image}/> : <View style={styles.imageFallback}><Ionicons name="image-outline" size={28} color="#9CA3AF"/></View>}<View style={{flex:1}}><Text style={styles.title}>{item.name}</Text><Text style={styles.sub}>{item.seller?.name} · ₦{Number(item.price).toLocaleString()}</Text><Text style={styles.description} numberOfLines={3}>{item.description}</Text></View></View></> : <><Text style={styles.title}>{item.seller?.name}</Text><Text style={styles.amount}>₦{Number(item.amount).toLocaleString()}</Text><Text style={styles.sub}>{item.bankAccount?.bankName} · {item.bankAccount?.accountNumber}</Text><Text style={styles.description}>{item.bankAccount?.accountName}</Text></>}<View style={styles.actions}><TouchableOpacity style={[styles.button,styles.reject]} onPress={()=>setRejecting(item)}><Text style={styles.buttonText}>Reject</Text></TouchableOpacity><TouchableOpacity style={[styles.button,styles.approve]} onPress={()=>approve(item)}><Text style={styles.buttonText}>Approve</Text></TouchableOpacity></View></View>;
  return <View style={styles.screen}><View style={styles.tabs}><TouchableOpacity style={[styles.tab,tab==='products'&&styles.tabActive]} onPress={()=>setTab('products')}><Text style={[styles.tabText,tab==='products'&&styles.tabTextActive]}>Listings</Text></TouchableOpacity><TouchableOpacity style={[styles.tab,tab==='payouts'&&styles.tabActive]} onPress={()=>setTab('payouts')}><Text style={[styles.tabText,tab==='payouts'&&styles.tabTextActive]}>Withdrawals</Text></TouchableOpacity></View>{loading?<View style={styles.center}><ActivityIndicator size="large" color="#F97316"/></View>:<FlatList data={items} renderItem={render} keyExtractor={item=>item._id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.center}><Ionicons name="checkmark-circle-outline" size={52} color="#16A34A"/><Text style={styles.empty}>Nothing awaiting review</Text></View>}/>}<Modal visible={!!rejecting} transparent animationType="fade" onRequestClose={()=>setRejecting(null)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>Reason for rejection</Text><TextInput style={styles.reason} value={reason} onChangeText={setReason} placeholder="Give the seller a clear reason" placeholderTextColor="#9CA3AF" multiline/><View style={styles.actions}><TouchableOpacity style={[styles.button,styles.cancel]} onPress={()=>setRejecting(null)}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity><TouchableOpacity style={[styles.button,styles.reject]} onPress={reject}><Text style={styles.buttonText}>Confirm rejection</Text></TouchableOpacity></View></View></View></Modal></View>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F7F9'},tabs:{flexDirection:'row',backgroundColor:'#FFF',padding:6,margin:14,borderRadius:14},tab:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:10},tabActive:{backgroundColor:'#111827'},tabText:{fontWeight:'700',color:'#6B7280'},tabTextActive:{color:'#FFF'},list:{padding:14,paddingBottom:40},card:{backgroundColor:'#FFF',borderRadius:16,padding:15,marginBottom:12,borderWidth:1,borderColor:'#E5E7EB'},productTop:{flexDirection:'row',gap:12},image:{width:88,height:88,borderRadius:12},imageFallback:{width:88,height:88,borderRadius:12,backgroundColor:'#F3F4F6',alignItems:'center',justifyContent:'center'},title:{fontSize:16,fontWeight:'800',color:'#111827'},sub:{fontSize:12,color:'#6B7280',marginTop:4},description:{fontSize:13,color:'#4B5563',lineHeight:18,marginTop:7},amount:{fontSize:24,fontWeight:'900',color:'#F97316',marginTop:8},actions:{flexDirection:'row',gap:10,marginTop:15},button:{flex:1,height:44,borderRadius:11,alignItems:'center',justifyContent:'center'},approve:{backgroundColor:'#16A34A'},reject:{backgroundColor:'#DC2626'},cancel:{backgroundColor:'#F3F4F6'},buttonText:{color:'#FFF',fontWeight:'800'},cancelText:{color:'#374151',fontWeight:'800'},center:{flex:1,minHeight:300,alignItems:'center',justifyContent:'center'},empty:{color:'#6B7280',fontWeight:'700',marginTop:12},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.45)',alignItems:'center',justifyContent:'center',padding:20},modal:{width:'100%',backgroundColor:'#FFF',borderRadius:18,padding:20},modalTitle:{fontSize:18,fontWeight:'900',color:'#111827'},reason:{height:110,backgroundColor:'#FFF',borderWidth:1,borderColor:'#D1D5DB',borderRadius:12,padding:13,color:'#111827',marginTop:14,textAlignVertical:'top'}});
